version: '3'
services:
  dev_database:
    image: postgres
    restart: always
    ports:
      - '5438:5432'
    environment:
      POSTGRES_DB: dev_rebel
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: